sudo: required
services:
  - docker

language: node_js
node_js:
  - "5"
  - "4"
  - "6"
  - "7"
  - "node"
  - "iojs"
cache: false

before_script:
   - ./test.sh

script:
   - sleep 2
   - npm test

env:
- CXX=g++-4.8


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

after_success:
- npm run coveralls