sudo: required
dist: trusty

language: node_js
node_js:
  - "0.12"
  - "iojs"
  - "stable"
  - "4.1"
  - "4.0"
  - "5.5"
cache: false

before_script:
   - test.sh

script:
   - ./test/box.lua &
   - sleep 2
   - npm run lint
   - npm test
