sudo: required
dist: trusty

language: node_js
node_js:
  - "5"
  - "4"
  - "6"
  - "7"
  - "node"
  - "iojs"
cache: false

before_script:
  - ./test.sh

script:
   - ./test/box.lua &
   - sleep 2
   - npm test
